# -*- coding: utf-8 -*-
"""ERTime_RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jjtmZ05K9OgKpPT0MLmi7hyYv2xIYsJ

# ERTime - Random Forest Model (Comparison)
## Emergency Room Wait Time Prediction
**AAI 595 - Applied Machine Learning**

Michael Lugo, Amoy Mowatt, Ardit Cana, Wesley Nabo

This notebook trains a **Random Forest Regressor** model to predict ER wait times and compares it against the Linear Regression baseline.
"""

# Essential imports for ER wait time prediction
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
np.random.seed(42)

# Configure plotting
plt.style.use('default')
sns.set_palette("husl")
print("✅ All imports successful!")
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")
print(f"Model: Random Forest Regressor (Comparison)")

"""## Load and Explore Dataset"""

# Load the cleaned ER dataset
df = pd.read_csv("cleaned_data.csv")

print(f"✅ Dataset loaded successfully!")
print(f"Dataset shape: {df.shape}")
print(f"Number of samples: {df.shape[0]}")
print(f"Number of features: {df.shape[1]}")
print(f"\nColumn names:")
for col in df.columns:
    print(f"  • {col} ({df[col].dtype})")

print(f"\nFirst 5 rows:")
df.head()

# Dataset statistics
print("Dataset Statistics:")
df.describe()

"""## Exploratory Data Analysis"""

plt.figure(figsize=(15, 10))

# Plot 1: Distribution of Target Variable
plt.subplot(2, 3, 1)
plt.hist(df["Total Wait Time (min)"], bins=40, edgecolor='black', alpha=0.7, color='forestgreen')
plt.xlabel("Total Wait Time (min)")
plt.ylabel("Frequency")
plt.title("Distribution of ER Wait Times")
plt.grid(True, alpha=0.3)

# Plot 2: Wait Time by Urgency Level
plt.subplot(2, 3, 2)
sns.boxplot(data=df, x="Urgency Level", y="Total Wait Time (min)",
            order=["Low", "Medium", "High", "Critical"])
plt.title("Wait Time by Urgency Level")
plt.grid(True, alpha=0.3)

# Plot 3: Wait Time by Region
plt.subplot(2, 3, 3)
sns.boxplot(data=df, x="Region", y="Total Wait Time (min)")
plt.title("Wait Time by Region")
plt.grid(True, alpha=0.3)

# Plot 4: Wait Time by Time of Day
plt.subplot(2, 3, 4)
sns.boxplot(data=df, x="Time of Day", y="Total Wait Time (min)")
plt.xticks(rotation=45)
plt.title("Wait Time by Time of Day")
plt.grid(True, alpha=0.3)

# Plot 5: Wait Time by Season
plt.subplot(2, 3, 5)
sns.boxplot(data=df, x="Season", y="Total Wait Time (min)")
plt.title("Wait Time by Season")
plt.grid(True, alpha=0.3)

# Plot 6: Correlation Heatmap (numeric features only)
plt.subplot(2, 3, 6)
numeric_cols = df.select_dtypes(include=[np.number]).columns
corr_matrix = df[numeric_cols].corr()
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm", center=0,
            square=True, linewidths=0.5)
plt.title("Feature Correlation Heatmap")

plt.tight_layout()
plt.show()

print("✅ Exploratory Data Analysis complete!")

"""## Feature Selection and Preprocessing

**Important:** We only use features available **before/at arrival**.

`Time to Registration`, `Time to Triage`, and `Time to Medical Professional` are process durations that literally sum to `Total Wait Time` — including them would be **data leakage** (R² = 1.0, meaningless).
"""

# Select features available BEFORE/AT arrival
feature_cols = [
    "Region", "Day of Week", "Season", "Time of Day", "Urgency Level",
    "Nurse-to-Patient Ratio", "Specialist Availability", "Facility Size (Beds)"
]

X = df[feature_cols].copy()
y = df["Total Wait Time (min)"].copy()

print(f"Feature columns selected: {len(feature_cols)}")
for col in feature_cols:
    print(f"  • {col}")
print(f"\nTarget variable: Total Wait Time (min)")
print(f"  Mean: {y.mean():.2f} minutes")
print(f"  Std:  {y.std():.2f} minutes")
print(f"  Min:  {y.min()} minutes")
print(f"  Max:  {y.max()} minutes")

"""## Encode Categorical Variables"""

# Encode categorical features using LabelEncoder
label_encoders = {}
categorical_cols = X.select_dtypes(include=["object", "string"]).columns

print("Encoding categorical variables...")
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    label_encoders[col] = le
    mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print(f"  ✅ '{col}': {mapping}")

print(f"\n✅ Feature matrix shape: {X.shape}")
print(f"✅ Target variable shape: {y.shape}")

"""## Standardize Features"""

# Standardize numerical features for consistency
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("✅ Features standardized using StandardScaler")
print(f"Feature means (should be ~0): {X_scaled.mean(axis=0).round(4)}")
print(f"Feature stds (should be ~1):  {X_scaled.std(axis=0).round(4)}")

"""## Train/Test Split
Using the same `random_state=42` as Linear Regression for a fair comparison.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

print(f"✅ Data split complete!")
print(f"Training set: {X_train.shape[0]} samples ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"Testing set:  {X_test.shape[0]} samples ({X_test.shape[0]/len(X)*100:.0f}%)")
print(f"\nTraining target - Mean: {y_train.mean():.2f}, Std: {y_train.std():.2f}")
print(f"Testing target  - Mean: {y_test.mean():.2f}, Std: {y_test.std():.2f}")

"""## Train the Random Forest Model"""

print("Training Random Forest model...")
print("=" * 50)

# Random Forest Hyperparameters
rf_model = RandomForestRegressor(
    n_estimators=100,       # Number of trees in the forest
    max_depth=None,         # Let trees grow fully
    min_samples_split=5,    # Minimum samples to split a node
    min_samples_leaf=2,     # Minimum samples at a leaf node
    random_state=42,
    n_jobs=-1               # Use all CPU cores for parallel training
)

rf_model.fit(X_train, y_train)

print("✅ Random Forest model trained successfully!")
print(f"\nModel Hyperparameters:")
print(f"  n_estimators:      {rf_model.n_estimators}")
print(f"  max_depth:         {rf_model.max_depth}")
print(f"  min_samples_split: {rf_model.min_samples_split}")
print(f"  min_samples_leaf:  {rf_model.min_samples_leaf}")
print(f"  Number of features: {rf_model.n_features_in_}")

"""## Make Predictions"""

y_train_pred = rf_model.predict(X_train)
y_test_pred = rf_model.predict(X_test)

print("✅ Predictions generated!")
print(f"\nSample predictions vs actual (first 10 test samples):")
print(f"{'Actual':>10} {'Predicted':>10} {'Error':>10}")
print("-" * 35)
for i in range(10):
    actual = y_test.iloc[i]
    predicted = y_test_pred[i]
    error = actual - predicted
    print(f"{actual:>10.1f} {predicted:>10.1f} {error:>10.1f}")

"""## Evaluation Metrics"""

# Training metrics
train_mae = mean_absolute_error(y_train, y_train_pred)
train_mse = mean_squared_error(y_train, y_train_pred)
train_rmse = np.sqrt(train_mse)
train_r2 = r2_score(y_train, y_train_pred)

# Testing metrics
test_mae = mean_absolute_error(y_test, y_test_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_rmse = np.sqrt(test_mse)
test_r2 = r2_score(y_test, y_test_pred)

print("=" * 55)
print("RANDOM FOREST - EVALUATION METRICS")
print("=" * 55)

print(f"\n{'Metric':<30} {'Training':>12} {'Testing':>12}")
print("-" * 55)
print(f"{'Mean Absolute Error (MAE)':<30} {train_mae:>12.2f} {test_mae:>12.2f}")
print(f"{'Mean Squared Error (MSE)':<30} {train_mse:>12.2f} {test_mse:>12.2f}")
print(f"{'Root Mean Squared Error (RMSE)':<30} {train_rmse:>12.2f} {test_rmse:>12.2f}")
print(f"{'R² Score':<30} {train_r2:>12.4f} {test_r2:>12.4f}")

# Diagnose the model
gap = train_r2 - test_r2
print(f"\n📊 Diagnostics:")
print(f"  Train-Test R² Gap: {gap:.4f}")
if gap > 0.1:
    print(f"  ⚠️  Possible overfitting (gap > 0.1)")
elif test_r2 < 0.5:
    print(f"  ⚠️  Possible underfitting (low R² score)")
else:
    print(f"  ✅ Model appears to generalize well")

"""## Cross-Validation"""

print("Performing 5-Fold Cross-Validation...")
print("=" * 50)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf_model, X_scaled, y, cv=kf, scoring='r2')

for fold, score in enumerate(cv_scores, 1):
    print(f"  Fold {fold}: R² = {score:.4f}")

print(f"\n✅ Cross-Validation Results:")
print(f"  Mean R²: {cv_scores.mean():.4f}")
print(f"  Std R²:  {cv_scores.std():.4f}")
print(f"  95% CI:  [{cv_scores.mean() - 1.96*cv_scores.std():.4f}, {cv_scores.mean() + 1.96*cv_scores.std():.4f}]")

"""## Feature Importance"""

importance_df = pd.DataFrame({
    "Feature": feature_cols,
    "Importance": rf_model.feature_importances_
}).sort_values("Importance", ascending=False)

print("Feature Importances (sorted by importance):")
print("=" * 50)
for _, row in importance_df.iterrows():
    bar_len = int(row["Importance"] * 40)
    bar = "█" * bar_len
    print(f"  {row['Feature']:<30} {row['Importance']:>8.4f} {bar}")

"""## Comprehensive Visualizations"""

plt.figure(figsize=(18, 12))

# Plot 1: Actual vs Predicted (Training)
plt.subplot(2, 3, 1)
plt.scatter(y_train, y_train_pred, alpha=0.3, edgecolors='k', linewidths=0.3, s=20, color='forestgreen')
plt.plot([y_train.min(), y_train.max()], [y_train.min(), y_train.max()],
         'r--', linewidth=2, label='Perfect Prediction')
plt.xlabel("Actual Wait Time (min)")
plt.ylabel("Predicted Wait Time (min)")
plt.title(f"Training: Actual vs Predicted (R²={train_r2:.4f})")
plt.legend()
plt.grid(True, alpha=0.3)

# Plot 2: Actual vs Predicted (Testing)
plt.subplot(2, 3, 2)
plt.scatter(y_test, y_test_pred, alpha=0.4, edgecolors='k', linewidths=0.3, s=20, color='darkorange')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         'r--', linewidth=2, label='Perfect Prediction')
plt.xlabel("Actual Wait Time (min)")
plt.ylabel("Predicted Wait Time (min)")
plt.title(f"Testing: Actual vs Predicted (R²={test_r2:.4f})")
plt.legend()
plt.grid(True, alpha=0.3)

# Plot 3: Residuals Distribution
plt.subplot(2, 3, 3)
residuals = y_test - y_test_pred
plt.hist(residuals, bins=40, edgecolor='black', alpha=0.7, color='forestgreen')
plt.axvline(x=0, color='red', linestyle='--', linewidth=2)
plt.xlabel("Residual (Actual - Predicted)")
plt.ylabel("Frequency")
plt.title(f"Residuals Distribution (Mean={residuals.mean():.2f})")
plt.grid(True, alpha=0.3)

# Plot 4: Residuals vs Predicted
plt.subplot(2, 3, 4)
plt.scatter(y_test_pred, residuals, alpha=0.4, edgecolors='k', linewidths=0.3, s=20, color='purple')
plt.axhline(y=0, color='red', linestyle='--', linewidth=2)
plt.xlabel("Predicted Wait Time (min)")
plt.ylabel("Residual")
plt.title("Residuals vs Predicted Values")
plt.grid(True, alpha=0.3)

# Plot 5: Feature Importances
plt.subplot(2, 3, 5)
imp_sorted = importance_df.sort_values("Importance", ascending=True)
plt.barh(imp_sorted["Feature"], imp_sorted["Importance"], color='forestgreen')
plt.xlabel("Importance")
plt.title("Feature Importances (Random Forest)")
plt.grid(True, alpha=0.3)

# Plot 6: Cross-Validation Scores
plt.subplot(2, 3, 6)
folds = range(1, len(cv_scores) + 1)
plt.bar(folds, cv_scores, alpha=0.7, color='forestgreen', edgecolor='black')
plt.axhline(y=cv_scores.mean(), color='red', linestyle='--',
            linewidth=2, label=f'Mean R²={cv_scores.mean():.4f}')
plt.xlabel("Fold")
plt.ylabel("R² Score")
plt.title("5-Fold Cross-Validation Scores")
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("✅ All visualizations complete!")

"""## Learning Curve Analysis (Bias-Variance Diagnostics)"""

def plot_learning_curve(model, X_train, y_train, X_test, y_test):
    """Generate learning curves to diagnose bias vs variance."""
    training_sizes = np.linspace(0.1, 1.0, 10)
    train_scores = []
    test_scores = []

    for size in training_sizes:
        n_samples = int(size * len(X_train))
        indices = np.random.choice(len(X_train), n_samples, replace=False)
        X_subset = X_train[indices]
        y_subset = y_train.iloc[indices] if hasattr(y_train, 'iloc') else y_train[indices]

        model.fit(X_subset, y_subset)

        train_pred = model.predict(X_subset)
        test_pred = model.predict(X_test)

        train_scores.append(r2_score(y_subset, train_pred))
        test_scores.append(r2_score(y_test, test_pred))

    return training_sizes, train_scores, test_scores

print("Generating learning curves...")
training_sizes, train_lc, test_lc = plot_learning_curve(
    RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    X_train, y_train, X_test, y_test
)

plt.figure(figsize=(10, 6))
sample_sizes = [int(size * len(X_train)) for size in training_sizes]
plt.plot(sample_sizes, train_lc, 'o-', label='Training R²', linewidth=2, markersize=6, color='forestgreen')
plt.plot(sample_sizes, test_lc, 'o-', label='Testing R²', linewidth=2, markersize=6, color='darkorange')
plt.xlabel("Training Set Size")
plt.ylabel("R² Score")
plt.title("Learning Curves - Random Forest")
plt.legend()
plt.grid(True, alpha=0.3)

# Diagnose from learning curves
final_gap = train_lc[-1] - test_lc[-1]
if final_gap > 0.15:
    diagnosis = "Overfitting (High Variance)"
elif max(test_lc) < 0.6:
    diagnosis = "Underfitting (High Bias)"
else:
    diagnosis = "Good Fit"

plt.text(0.05, 0.05, f"Diagnosis: {diagnosis}",
         transform=plt.gca().transAxes,
         bbox=dict(boxstyle="round", facecolor='wheat'),
         verticalalignment='bottom', fontsize=12)

plt.tight_layout()
plt.show()

print(f"✅ Learning curve diagnosis: {diagnosis}")

# Retrain on full training set (learning curve modifies the model)
rf_model.fit(X_train, y_train)

"""## Model Summary"""

print("=" * 50)
print("RANDOM FOREST MODEL - SUMMARY")
print("=" * 50)
print(f"  Dataset:         {df.shape[0]} samples, {len(feature_cols)} features")
print(f"  Train/Test:      {X_train.shape[0]}/{X_test.shape[0]} (80/20 split)")
print(f"  n_estimators:    {rf_model.n_estimators}")
print(f"  Test MAE:        {test_mae:.2f} minutes")
print(f"  Test RMSE:       {test_rmse:.2f} minutes")
print(f"  Test R²:         {test_r2:.4f}")
print(f"  CV Mean R²:      {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
print(f"  Top Feature:     {importance_df.iloc[0]['Feature']} ({importance_df.iloc[0]['Importance']:.4f})")
print("=" * 50)